apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  local:
    path: /var/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: environment
          operator: In
          values:
          - dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-volume