apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: persistantvolume1
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi